// <auto-generated />
namespace SellUsed.DataContexts.ProductDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFavoriteAds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFavoriteAds));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071323442_AddFavoriteAds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
